name: Destroy Langfuse

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: false
        default: "us-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy Langfuse Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::876581797419:role/github-actions
          aws-region: ${{ github.event.inputs.region }}
          role-session-name: github-actions

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Create Virtual Environment & Install Dependencies
        working-directory: langfuse-v3
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Create cdk.context.json from secret
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "langfuse-v3/cdk.context.json"
          json: ${{ secrets.CDK_CONTEXT_JSON }}

      - name: Destroy CDK Stacks
        working-directory: langfuse-v3
        run: |
          source .venv/bin/activate
          export CDK_DEFAULT_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
          export CDK_DEFAULT_REGION=$(aws configure get region)
          npx cdk destroy --all --force --require-approval never
